# Generated by Django 4.1.7 on 2023-03-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_sale_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='ammountReceived',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
